apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-app
  template:
    metadata:
      labels:
        app: gke-app
    spec:
      containers:
      - name: gke-app
        image: asia-south1-docker.pkg.dev/mineral-hangar-453509-r7/my-docker-repo/batch-job@sha256:242f2b1ccdb846c59d9a0a4eb9c90176734ae8a70525b301c86d7814fc68ed7f
        ports:
        - containerPort: 3000
