apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-app
  template:
    metadata:
      labels:
        app: gke-app
    spec:
      containers:
      - name: gke-app
        image: us-central1-docker.pkg.dev/internal-sandbox-446612/my-docker-repo/batch_job
        ports:
        - containerPort: 3000
