name: Deploy to GKE with GCE Ingress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gke-repo/gke-app:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gke-repo/gke-app:latest

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials gke-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Application to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml

    - name: Verify Deployment
      run: kubectl get pods,svc,ingress
