name: Deploy to GKE with GCE Ingress  

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: halogen-acumen-454303-k2
  ARTIFACT_REGION: us-central1
  ARTIFACT_REPO: my-docker-repo
  IMAGE_NAME: batch-job
  CLUSTER: gkefleet-cluster-1
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Build and Push Docker Image
      id: build-image
      run: |
        IMAGE_TAG=${{ github.sha }}  # Using commit SHA for tagging
        docker build -t ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} .
        docker push ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID

    - name: Deploy Application to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml

    - name: Verify Deployment
      run: kubectl get pods,svc,ingress
